# Generated by Django 6.0.4 on 2026-04-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('article_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_size_mb', models.FloatField()),
                ('row_count', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('data_type', models.CharField(max_length=100)),
                ('character_set', models.CharField(default='UTF-8', max_length=20)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_articles', models.IntegerField()),
                ('model_accuracy', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('ai_confidence', models.CharField(max_length=20)),
                ('cohesion', models.FloatField()),
                ('overlap', models.FloatField()),
                ('entropy', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Model Metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=50)),
                ('confidence', models.IntegerField()),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.category')),
            ],
        ),
    ]
